change lintr URLs to r-lib org
r-lib/lintr pull request #1125
Opened 2022-05-06 16:33 UTC by dpprdan

This replaces `jimhester` with `r-lib` in the GitHub URLs / repo address.

Questions:

1. The URL in the `lint-changed-file.yaml` needs to be changed as well, I assume?
    https://github.com/r-lib/lintr/blob/4ca7e484bcbe538cc5a81338c0ec55a0ae084cb0/.github/workflows/lint-changed-files.yaml#L35
2. Is the [gitter chat](https://github.com/dpprdan/lintr/blob/9fa72489b5d641312ca7c27128599298a7f0b506/README.md?plain=1#L5) still maintained? The last activity was over a year ago, AFAICT.

2022-05-06 21:45 UTC, AshesITR requested changes
Thanks for this PR! Just a few things need adapting.

2022-05-06 21:45 UTC, AshesITR commented on README.md
> +[![R build status](https://github.com/r-lib/lintr/workflows/R-CMD-check/badge.svg)](https://github.com/jimhester/lintr/actions)
The link targets also contain /jimhester URLs

2022-05-09 09:52 UTC, dpprdan commented
> Questions:
> 
> 1. The URL in the `lint-changed-file.yaml` needs to be changed as well, I assume?
>        https://github.com/r-lib/lintr/blob/4ca7e484bcbe538cc5a81338c0ec55a0ae084cb0/.github/workflows/lint-changed-files.yaml#L35
> 2. Is the [gitter chat](https://github.com/dpprdan/lintr/blob/9fa72489b5d641312ca7c27128599298a7f0b506/README.md?plain=1#L5) still maintained? The last activity was over a year ago, AFAICT.


Can you comment on these, @AshesITR?

2022-05-09 10:34 UTC, AshesITR commented
I think it should be safe to substitute all occurrences of `jimhester` with `r-lib` for `github.com` URLs.
Regarding codecov, I don't know. @jimhester do you know if the codecov repo needs moving?

I've personally never looked at the gitter channel, not sure about the other maintainers, though.

cc @MichaelChirico

2022-05-09 10:38 UTC, AshesITR approved these changes

2022-05-09 14:44 UTC, MichaelChirico commented
also haven't looked at gitter

2022-05-09 14:44 UTC, MichaelChirico approved these changes

2022-05-09 14:55 UTC, dpprdan commented
> Regarding codecov, I don't know. @jimhester do you know if the codecov repo needs moving?

Most recent commit on [`jimhester`](https://codecov.io/github/jimhester/lintr?branch=master) is 6 months old, whereas [`r-lib`](https://codecov.io/github/r-lib/lintr?branch=master) a few minutes ago. So I'd say this needs moving.

> also haven't looked at gitter

Sounds unmaintained, so I'll delete the link then?

2022-05-16 02:27 UTC, MichaelChirico commented
Merging for now. Jim, feel free to mention any changes we should revert later.

2022-05-16 02:48 UTC, merged