New trailing_assignment_linter
r-lib/lintr pull request #1490
Opened 2022-07-31 11:04 UTC by ashbaldry

This might just be a personal pet peeve, but the trailing_assignment_linter flags when assignments are at the end of the line.

Examples:
```r
y <- mean(x, na.rm =
  TRUE
)

some_long_variable_name <-
  function_name(...)
```

2022-07-31 11:12 UTC, IndrajeetPatil commented on R/trailing_assignment_linter.R
> +    bad_lines <- which(!vapply(res[, 1], is.na, logical(1), USE.NAMES = FALSE))
This is creating a `implicit_integer_linter()` lint.

```suggestion
    bad_lines <- which(!vapply(res[, 1], is.na, 1L, USE.NAMES = FALSE))
```

2022-07-31 11:12 UTC, IndrajeetPatil commented on R/trailing_assignment_linter.R
> +          column_number = 1,
Same here:

```suggestion
          column_number = 1L,
```

2022-07-31 11:13 UTC, IndrajeetPatil commented on R/trailing_assignment_linter.R
> +            "Assignment `", res[line, 1], "` should not be trailing at end of line"
```suggestion
            "Assignment `", res[line, 1L], "` should not be trailing at end of line"
```

2022-07-31 11:14 UTC, IndrajeetPatil commented
Thanks, @ashbaldry!

Do you mind creating an issue that this PR will close? 

Ideally, we like to discuss the new linters in an issue, so that the issue number can be mentioned in the `NEWS.md` for future reference.

2022-07-31 11:21 UTC, ashbaldry commented
@IndrajeetPatil thanks for the feedback; I have created #1491 for reference

2022-07-31 17:38 UTC, IndrajeetPatil commented
Examples of the current behavior:

``` r
library(lintr)

lint(
  text = "x <- 5",
  linters = trailing_assignment_linter()
)

lint(
  text = "x <-
  5",
  linters = trailing_assignment_linter()
)
#> <text>:1:1: style: [trailing_assignment_linter] Assignment `<-` should not be trailing at end of line
#> x <-
#> ^

lint(
  text = "y <- mean(x, na.rm =
            TRUE
          )",
  linters = trailing_assignment_linter()
)
#> <text>:1:1: style: [trailing_assignment_linter] Assignment `=` should not be trailing at end of line
#> y <- mean(x, na.rm =
#> ^

lint(
  text = "some_long_variable_name <-
  function_name(...)",
  linters = trailing_assignment_linter()
)
#> <text>:1:1: style: [trailing_assignment_linter] Assignment `<-` should not be trailing at end of line
#> some_long_variable_name <-
#> ^

lint(
  text = "iris_long <-
  iris %>%
  gather(measure, value, -Species) %>%
  arrange(-value)"
  ,
  linters = trailing_assignment_linter()
)

lint(
  text = "iris_long <- iris %>%
  gather(measure, value, -Species) %>%
  arrange(-value)",
  linters = trailing_assignment_linter()
)

lint(
  text = "iris %>%
  gather(measure, value, -Species) %>%
  arrange(-value) ->
  iris_long",
  linters = trailing_assignment_linter()
)
```

<sup>Created on 2022-07-31 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

2022-08-02 10:15 UTC, IndrajeetPatil commented
@ashbaldry Can you please also update `NEWS.md` to log this new addition? Thanks.

2022-08-03 17:21 UTC, IndrajeetPatil submitted a review, later dismissed
LGTM! Thanks a lot, @ashbaldry.

I will still wait to see if @MichaelChirico has any comments/concerns about the PR and then merge.

2022-08-09 05:40 UTC, AshesITR requested changes

2022-08-09 05:40 UTC, AshesITR commented on R/assignment_linter.R
> +    "[@line1 < following-sibling::*[1]/@line1]"
This might mess up with comments.

```r
a <- # comment
  42L
```

2022-08-09 05:40 UTC, AshesITR commented on R/assignment_linter.R
> +    ),
Remove disallowed assignment operators here to avoid duplicate lints for them.

2022-08-09 05:40 UTC, AshesITR commented on tests/testthat/test-assignment_linter.R
> +    "iris %>%\n  gather(measure, value, -Species) %>%\n  arrange(\n    -value\n    ) ->>\n  iris_long",
These should be more readable if you use the helper `trim_some()`.

2022-08-09 18:47 UTC, ashbaldry commented
Thanks for the feedback @AshesITR, between the comments and the post on the issue I think I have understood. I have handled the situation where a comment is next and added a test for it, and made sure that it doesn't supersede the current assignment linters. 

Do let me know if I've left anything out!

2022-08-09 20:29 UTC, AshesITR approved these changes
LGTM, thanks a lot!

2022-08-09 20:29 UTC, AshesITR commented on R/assignment_linter.R
> +      trailing_assignments <- xml2::xml_attrs(bad_expr) %in% xml2::xml_attrs(bad_trailing_expr)
Very smart 👍

2022-08-09 20:51 UTC, merged

2022-08-10 07:45 UTC, IndrajeetPatil commented
Thanks a lot, @ashbaldry! 👏

P.S. A big fan of `{designer}`! ☺️