Use raw strings in some places
r-lib/lintr pull request #2604
Opened 2024-06-12 06:52 UTC by MichaelChirico

NB: Based against `r-40` (#2603).

Just to give an example of what's available to us with an R 4.0 dependency. I'm sure there's more. I'm also fairly confident tests will fail here :sweat_smile:

2024-06-12 07:11 UTC, IndrajeetPatil commented
> I'm also fairly confident tests will fail here 😅

You underestimate yourself, sir 😃 

The tests look much cleaner now!

2024-06-12 21:31 UTC, AshesITR commented
Checks need to be triggered here somehow.
The change LGTM.

2024-06-13 05:38 UTC, AshesITR requested changes

2024-06-13 05:38 UTC, AshesITR commented on NEWS.md
> +* {lintr} now depens on R version 4.0.0. It already does so implicitly due to recursive upstream dependencies requiring this version; we've simply made that dependency explicit and up-front (#2569, @
Merge failed

2024-06-14 08:31 UTC, IndrajeetPatil approved these changes

2024-06-15 08:32 UTC, AshesITR approved these changes

2024-06-15 08:42 UTC, merged