re_matches_logical helper ensures logical output of re_matches_logical
r-lib/lintr pull request #2679
Opened 2024-10-27 17:29 UTC by MichaelChirico

Closes #2678. Still needs tests, NEWS.

2024-10-27 21:50 UTC, MichaelChirico commented
All of the fixes are for dev-only features, so didn't update any NEWS.

2024-10-29 05:19 UTC, AshesITR commented
I thunk we should add a bullet stating that some linters, and `expect_lint()` now support capture groups in their regex.

2024-11-28 05:44 UTC, AshesITR requested changes
Let's add to NEWS that support for regex with capture groups was added for some linters.

2024-12-02 06:38 UTC, MichaelChirico commented
> Let's add to NEWS that support for regex with capture groups was added for some linters.

OK, PTAL. The thing is, the changes to `return_linter()` and `todo_comment_linter()` are dev-only, so a NEWS item doesn't make sense. The change for `object_usage_linter()` is not user-visible.

2024-12-02 06:41 UTC, MichaelChirico commented on NEWS.md
> +* `unreachable_code_linter()` is less strict about whether `allow_comment_regex=` contains capture groups (#2678, @MichaelChirico).
```suggestion
* Some code with parameters accepting regular expressions is less strict about whether there are capture groups  (#2678, @MichaelChirico). In particular, this affects `unreachable_code_linter(allow_comment_regex=)` and `expect_lint(checks=)`.
```

2024-12-03 01:14 UTC, AshesITR approved these changes

2024-12-03 01:30 UTC, merged