Allow assignment generics on custom classes object name lintr
r-lib/lintr pull request #843
Opened 2021-07-24 14:05 UTC by jonkeane

For assignment methods like `names<-.class_name` I'm seeing linting errors:

```
> lintr::lint(text = "`names<-.my_custom_class` <- function() 2", linters = lintr::object_name_linter())
<text>:1:1: style: Variable and function name style should be snake_case or symbols.
`names<-.my_custom_class` <- function() 2
```

This PR resolves this (by looking for `<-.` and replacing it with `.`, in `strip_names()` since the `<-` are stripped from the generics before they are used in the matching regex in the object name lintr. 

Alternatively, I could try keeping `<-` in both the generic list and the function names that are being linted if we think that's a better approach.

2021-08-19 12:39 UTC, AshesITR commented
Thanks for reporting this bug.
The actual problem here seems to be that `strip_names` strips too much.

    `names<-`

is in `.S3PrimitiveGenerics` and thus should be considered to be a generic in and of itself. I'd prefer to fix the detection rather than automatically assume all `<-`-functions are generic if and only if their non-setter versions are.

2021-09-16 13:44 UTC, jonkeane commented
I'm happy to try removing `strip_names()` from the generics detection and seeing if the tests pass / using the `compare_branches.R` script to check if there are any regressions.

2022-03-28 12:07 UTC, AshesITR commented
Hi @jonkeane, sorry for the late reply.
I've just locally tested removing `strip_names()` from the generics call and didn't notice any adverse side-effects.
So this really seems like the best way to fix the issue.

2022-03-28 13:48 UTC, jonkeane commented
Is there anything you need from me to get this finished?

2022-03-28 15:09 UTC, AshesITR commented
Just a few tiny things still need to be done:

 1. revert the change to `strip_names()`
 2. remove the `strip_names()` call from https://github.com/r-lib/lintr/blob/be7a7f2827bbabdc3e80c77929b9986244b21fe9/R/object_name_linters.R#L65
 3. Add a bullet the NEWS, crediting yourself and citing this PR number (since there is no associated issue IINM)

2022-03-28 18:19 UTC, jonkeane commented
Thanks for the follow up — I've done all three of those. I put the news at the end of the current list, but happy to move it elsewhere if that's perferable.

2022-03-28 19:12 UTC, AshesITR requested changes
Thank you very much, almost ready to merge.

2022-03-28 19:12 UTC, AshesITR commented on NEWS.md
> +* Assignment generics on custom classes (#843, @jonkeane)
Maybe ` * `object_name_linter()` now correctly detects assignment generics (#843, @jonkeane)`?

2022-03-28 20:11 UTC, jonkeane commented on NEWS.md
> +* Assignment generics on custom classes (#843, @jonkeane)
```suggestion
* `object_name_linter()` now correctly detects assignment generics (#843, @jonkeane)
```

2022-03-28 20:11 UTC, jonkeane commented
Done, and thank you, again!

2022-03-28 20:43 UTC, merged